version: "3.1"

services:
  app:
    image: "afa4e7176bed375f0b5df41d260643416ca89f3fe5329f1129af1cba0c168265"
    container_name: app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db

  db:
    image: "postgres"
    container_name: db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
